var dir_b2f33c71d4aa5e7af42a1ca61ff5af1b =
[
    [ "AIEasy.java", "_a_i_easy_8java_source.html", null ],
    [ "ConnectFour.java", "_connect_four_8java_source.html", null ],
    [ "ConnectFourAI.java", "_connect_four_a_i_8java_source.html", null ],
    [ "ConnectFourLoader.java", "_connect_four_loader_8java_source.html", null ],
    [ "ConnectFourSaver.java", "_connect_four_saver_8java_source.html", null ],
    [ "Controls.java", "_controls_8java_source.html", null ],
    [ "Coordinate.java", "_coordinate_8java_source.html", null ],
    [ "Drawing.java", "_drawing_8java_source.html", null ],
    [ "EndDisplay.java", "_end_display_8java_source.html", null ],
    [ "FileManager.java", "_file_manager_8java_source.html", null ],
    [ "Game.java", "_game_8java_source.html", null ],
    [ "GameBoardControls.java", "_game_board_controls_8java_source.html", null ],
    [ "GameBoardGraphics.java", "_game_board_graphics_8java_source.html", null ],
    [ "GameSelecter.java", "_game_selecter_8java_source.html", null ],
    [ "GameWindow.java", "_game_window_8java_source.html", null ],
    [ "Grid.java", "_grid_8java_source.html", null ],
    [ "Human.java", "_human_8java_source.html", null ],
    [ "Loader.java", "_loader_8java_source.html", null ],
    [ "Othello.java", "_othello_8java_source.html", null ],
    [ "OthelloAI.java", "_othello_a_i_8java_source.html", null ],
    [ "OthelloLoader.java", "_othello_loader_8java_source.html", null ],
    [ "OthelloSaver.java", "_othello_saver_8java_source.html", null ],
    [ "Player.java", "_player_8java_source.html", null ],
    [ "PlayerSettings.java", "_player_settings_8java_source.html", null ],
    [ "Saver.java", "_saver_8java_source.html", null ],
    [ "Timer.java", "_timer_8java_source.html", null ]
];